### PR TITLE
Update service.py

### PR DESCRIPTION
**Pull request by ainur-fa**
the variable log_batch_size was ignored during initialization

### CODE REVIEW

**Comment by iivanou** [comment]
This variable is not currently used. No need to initialize it.

**Comment by ainur-fa** [comment]
then why is it in the list of optional parameters in the pytest.ini file if it is hardcoded to a value of 20?

**Comment by iivanou** [comment]
> then why is it in the list of optional parameters in the pytest.ini file if it is hardcoded to a value of 20?

You can remove it from the pytest.ini. This value will be used later when we finish up a brand new client that supports batching.

**Comment by ainur-fa** [comment]
I'm understood, thank you

**Pull request closed without merging**
