### PR TITLE
Restore rp_display_suite_test_file and fix bug with rp_dir_level

### PR DESCRIPTION
**Pull request by ramir-dn**
Hellow,

This PR handles 2 things:
1. Fixes an issue with `rp_dir_level`: in `_remove_root_dirs`, the loop that handles the ROOT node only handled it first child and called `return`.
2. Add back the support for `rp_display_suite_test_file`. It depends on `rp_dir_level` in a way that if the file name appears deep in the hierarchy, it will be kept and not deleted. The default is `True` to keep the current behavior, but if set to `False`, and the `rp_dir_level` is deep enough, the file name will be removed too, and will be left with suites and tests only in the hierarchy.

### CODE REVIEW

**Comment by ramir-dn** [comment]
Hello @HardNorth , will be great if you could take a look and review this. If that's fine, it will be great to have a new release with this change. thanks!

**Comment by ramir-dn** [comment]
Hi @HardNorth, anything I can do to promote this PR? thanks you!

**Review by HardNorth — CHANGES_REQUESTED** [review]
@ramir-dn, Thanks for the suggestion, but looks like you checked out broken code which was in develop branch for one day. Please pull the latest changes.

**Comment by ramir-dn** [comment]
@HardNorth , I fixed the missing parameter. I am not sure what happened in my local tox run but it didn't detect it. Can you please rerun?

**Review by HardNorth — APPROVED** [review]
LGTM

**Comment by ramir-dn** [comment]
Thanks @HardNorth!
Can you tell when can I expect a new release with this fix?

**Comment by HardNorth** [comment]
@ramir-dn Please wait for a day or two. I have to rework your code and add tests.

**Comment by HardNorth** [comment]
@ramir-dn Please use this version: https://github.com/reportportal/agent-python-pytest/releases/tag/5.4.6
I renamed your flag to `rp_hierarchy_test_file`, to conform with other flags and removed any chain with `rp_hierarchy_dirs_level` flag, so you can use it independently.

**Comment by ramir-dn** [comment]
That was quick! Thanks @HardNorth!

**Pull request merged**
