### PR TITLE
added the fix to attach screenshots

### PR DESCRIPTION
**Pull request by surevs**
Based on discussion happened at #70 raised   This becomes a very needy hack to be integrated into release

### CODE REVIEW

**Comment by filland** [comment]
@s0undt3ch @krasoffski @frizzby @ramriddick guys, can anyone look at the PR ?

**Comment by filland** [comment]
@surevs hi, take a look please

**Comment by surevs** [comment]
@krasoffski and @filland - sorry about the delay, performed a merge of both conditions as per review comments. thanks

**Comment by ehaelyon** [comment]
Hi,
I have installed pytest-reportportal 1.0.4 on my workstation - in which version does this fix is entered?
Please don't say 1.0.5 because I have installed it at first and it didn't work well :/
A workaround of yours said to decrease version to 1.0.4

**Comment by krasoffski** [comment]
Version `1.0.6` contains this fix. There is tag for this but new version `1.0.6` has not been uploaded to pypi accidentally.

image

**Comment by ehaelyon** [comment]
Hi Yuri,

Thank you for your reply!
When will you upload pytest-reportportal 1.0.6 to pypi?
Currently I see that

[cid:image001.png@01D51222.3575D380][cid:image002.png@01D51222.3575D380]

Best Regards,

Eden Haelyon


Automation Engineer
M:
+972-52-6410369
[ers/barzrihan/Library/Containers/com.microsof]
T:
None
E:
ehaelyon@drivenets.com<mailto:ehaelyon@drivenets.com>

**Comment by krasoffski** [comment]
@filland 
Could you, please, upload new version to PyPI?
I see PR #113  but there is no new package released (or need to fix release pipeline).

**Comment by ehaelyon** [comment]
Hi Yury,

There are still few questions that I would like to ask as I did not receive an answer for them on my previous email
It seems like you have a serious bug in version 1.0.5 and I want to understand if it gets fixed in version 1.0.6
In addition, I want to know few more things on the product itself.

We want to implement ReportPortal in our production automation environment, but we must verify few things first

My number is +972-526410369 – I will be grateful if you or someone else from ReportPortal support could contact me today.

Best Regards,

Eden Haelyon


Automation Engineer
M:
+972-52-6410369
[ers/barzrihan/Library/Containers/com.microsof]
T:
None
E:
ehaelyon@drivenets.com<mailto:ehaelyon@drivenets.com>

**Comment by filland** [comment]
@ehaelyon 
Please, ask your questions related to implementation RP in your production in our slack https://reportportal-slack-auto.herokuapp.com/

**Comment by filland** [comment]
@krasoffski @ehaelyon @surevs a new version with latest updates published
https://pypi.org/project/pytest-reportportal/1.0.7/

**Pull request merged**
