### PR TITLE
Make tests that skip in setup phase not require investigation in reportportal

### PR DESCRIPTION
**Pull request by kleptog**
They will receive the "skip" label so you can distinguish them, so they
require no further action in the interface.  If a test throws skip during
that actual test itself it will still show as "skipped" in reportportal.

Fixes: reportportal/agent-python-pytest#58

### CODE REVIEW

**Comment by kleptog** [comment]
I think the problem comes down to differing meanings for "skip". RP assumes a test that is skipped is because something happened that needs investigation (precondition not met). In Python "skip" means that the test is not relevant for the current configuration.

With this code we distinguish these cases by whether the skip is in the test setup, or in the execution. Which seems to me to be the correct approach.

An alternative is what the java client does which is make a global option to keep them as "skipped" but mark them as not being an issue (https://github.com/reportportal/client-java/blob/2efdec2524b77a12c004cbf32780d8d8bd5a0779/src/main/java/com/epam/reportportal/service/LaunchImpl.java#L248-L252). I'm not a fan because this means that *all* skipped test will no longer be issues, which seems too far the other way. I'd prefer to give developers the flexibility.

**Comment by DzmitryHumianiuk** [comment]
@kleptog @krasoffski Hi,
I'll not agree on the way to send python-skip as PASSED. cause you influence on actual result of passed test cases.

Send it as skipped sounds more reasonable. Since it's skipped in reality.

And if you know, those skipped tests are python-skip, you can follow the way how java agent does it: send it with NOT_ISSUE.

But if you can differentiate that skipped test skipped because of any issue, send it as regular skipped test. And RP will assign `To Investigate` for it.

Does it make sense?

**Comment by kleptog** [comment]
@DzmitryHumianiuk @krasoffski
I understand, I have just uploaded a new patch which does it that way. Now it works as follows:

```
# This will not require investigation.
@pytest.mark.skip(reason="Not relevant here")
def test_foo():
    pass

# This will require investigation
def test_bar():
    raise skip("Service unavailable")
```

Incidentally, any chance of a release soon? With this change the master branch will actually work for us (and actually found some issues).

**Comment by DzmitryHumianiuk** [comment]
@krasoffski it's good to go now?
we can merge it?

**Comment by DzmitryHumianiuk** [comment]
@krasoffski thank you

**Pull request merged**
