### PR TITLE
Fixes for async v5 support

### PR DESCRIPTION
**Pull request by Mephody**

### CODE REVIEW

**Comment by iivanou** [comment]
NOTE: This will only work having changes https://github.com/reportportal/agent-python-pytest/pull/146/files applied to the client.

**Comment by Mephody** [comment]
> NOTE: This will only work having changes https://github.com/reportportal/agent-python-pytest/pull/146/files applied to the client.

I think you mean this https://github.com/reportportal/client-Python/pull/62 should be applied to the client.

**Comment by rplevka** [comment]
@Mephody is logging working too?
I checked out your branch together with https://github.com/reportportal/client-Python/pull/62
and i can't get the logging working.
Looks like you didn't touch `post_logs` method. it  should accept the `launchUuid` and `testItemUuid` in order to to construct a valid payload for `/log` endpoint.
while `launchUuid` is accessible in that scope (`self.RP.launch_id`), I'm struggling with the `item_id`, since this one is kept in the listener and I don't know how to pass it.

**Comment by liiight** [comment]
I really like to see this finished and merged. I'm more than willing to contribute time and effort to make this happen if needed.

**Comment by g-bon** [comment]
> I really like to see this finished and merged. I'm more than willing to contribute time and effort to make this happen if needed.

same here, it would be great to have pytest hooked to v5, happy to help

**Comment by liiight** [comment]
Seems that #69 is now merged, could this be merged as well?

**Comment by iivanou** [comment]
Pulled in #164.

**Pull request closed without merging**
